clear all;
close all;

frac_laplacian_settings;

plot_figures(data_prefix, f_ex, ...
    method_list, truncation_length_list, ...
    figure_prefix);

plot_figures_thick_restart(data_prefix, f_ex, ...
    method_list, truncation_length_list, ...
    figure_prefix);