clear all;
close all;
warning off;

frac_laplacian_settings_thick_restart;

run_methods_thick_restart(data_prefix, ...
    method_list, ...
    truncation_length_list, ...
    basic_param, ...
    max_num_quad_points, ...
    sketching_mat_type, sketching_size, ...
    sketching_size_control, cond_tol, ...
    A, b);
